// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.21.5
// source: source/filters/http/proto/ensure-variables.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LocationType int32

const (
	LocationType_header      LocationType = 0
	LocationType_cookie      LocationType = 1
	LocationType_queryString LocationType = 2
	LocationType_metadata    LocationType = 3
)

// Enum value maps for LocationType.
var (
	LocationType_name = map[int32]string{
		0: "header",
		1: "cookie",
		2: "queryString",
		3: "metadata",
	}
	LocationType_value = map[string]int32{
		"header":      0,
		"cookie":      1,
		"queryString": 2,
		"metadata":    3,
	}
)

func (x LocationType) Enum() *LocationType {
	p := new(LocationType)
	*p = x
	return p
}

func (x LocationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocationType) Descriptor() protoreflect.EnumDescriptor {
	return file_source_filters_http_proto_ensure_variables_proto_enumTypes[0].Descriptor()
}

func (LocationType) Type() protoreflect.EnumType {
	return &file_source_filters_http_proto_ensure_variables_proto_enumTypes[0]
}

func (x LocationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocationType.Descriptor instead.
func (LocationType) EnumDescriptor() ([]byte, []int) {
	return file_source_filters_http_proto_ensure_variables_proto_rawDescGZIP(), []int{0}
}

type EnsureVariablesConfig_Rule_Value_MatchType int32

const (
	EnsureVariablesConfig_Rule_Value_exact  EnsureVariablesConfig_Rule_Value_MatchType = 0
	EnsureVariablesConfig_Rule_Value_prefix EnsureVariablesConfig_Rule_Value_MatchType = 1
	EnsureVariablesConfig_Rule_Value_suffix EnsureVariablesConfig_Rule_Value_MatchType = 2
	EnsureVariablesConfig_Rule_Value_regex  EnsureVariablesConfig_Rule_Value_MatchType = 3
)

// Enum value maps for EnsureVariablesConfig_Rule_Value_MatchType.
var (
	EnsureVariablesConfig_Rule_Value_MatchType_name = map[int32]string{
		0: "exact",
		1: "prefix",
		2: "suffix",
		3: "regex",
	}
	EnsureVariablesConfig_Rule_Value_MatchType_value = map[string]int32{
		"exact":  0,
		"prefix": 1,
		"suffix": 2,
		"regex":  3,
	}
)

func (x EnsureVariablesConfig_Rule_Value_MatchType) Enum() *EnsureVariablesConfig_Rule_Value_MatchType {
	p := new(EnsureVariablesConfig_Rule_Value_MatchType)
	*p = x
	return p
}

func (x EnsureVariablesConfig_Rule_Value_MatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnsureVariablesConfig_Rule_Value_MatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_source_filters_http_proto_ensure_variables_proto_enumTypes[1].Descriptor()
}

func (EnsureVariablesConfig_Rule_Value_MatchType) Type() protoreflect.EnumType {
	return &file_source_filters_http_proto_ensure_variables_proto_enumTypes[1]
}

func (x EnsureVariablesConfig_Rule_Value_MatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnsureVariablesConfig_Rule_Value_MatchType.Descriptor instead.
func (EnsureVariablesConfig_Rule_Value_MatchType) EnumDescriptor() ([]byte, []int) {
	return file_source_filters_http_proto_ensure_variables_proto_rawDescGZIP(), []int{1, 0, 0, 0}
}

type EnsureVariablesConfig_Rule_CopyTo_Direction int32

const (
	EnsureVariablesConfig_Rule_CopyTo_default  EnsureVariablesConfig_Rule_CopyTo_Direction = 0
	EnsureVariablesConfig_Rule_CopyTo_request  EnsureVariablesConfig_Rule_CopyTo_Direction = 1
	EnsureVariablesConfig_Rule_CopyTo_response EnsureVariablesConfig_Rule_CopyTo_Direction = 2
	EnsureVariablesConfig_Rule_CopyTo_both     EnsureVariablesConfig_Rule_CopyTo_Direction = 3
)

// Enum value maps for EnsureVariablesConfig_Rule_CopyTo_Direction.
var (
	EnsureVariablesConfig_Rule_CopyTo_Direction_name = map[int32]string{
		0: "default",
		1: "request",
		2: "response",
		3: "both",
	}
	EnsureVariablesConfig_Rule_CopyTo_Direction_value = map[string]int32{
		"default":  0,
		"request":  1,
		"response": 2,
		"both":     3,
	}
)

func (x EnsureVariablesConfig_Rule_CopyTo_Direction) Enum() *EnsureVariablesConfig_Rule_CopyTo_Direction {
	p := new(EnsureVariablesConfig_Rule_CopyTo_Direction)
	*p = x
	return p
}

func (x EnsureVariablesConfig_Rule_CopyTo_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnsureVariablesConfig_Rule_CopyTo_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_source_filters_http_proto_ensure_variables_proto_enumTypes[2].Descriptor()
}

func (EnsureVariablesConfig_Rule_CopyTo_Direction) Type() protoreflect.EnumType {
	return &file_source_filters_http_proto_ensure_variables_proto_enumTypes[2]
}

func (x EnsureVariablesConfig_Rule_CopyTo_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnsureVariablesConfig_Rule_CopyTo_Direction.Descriptor instead.
func (EnsureVariablesConfig_Rule_CopyTo_Direction) EnumDescriptor() ([]byte, []int) {
	return file_source_filters_http_proto_ensure_variables_proto_rawDescGZIP(), []int{1, 0, 1, 0}
}

type CookieOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HttpOnly bool   `protobuf:"varint,1,opt,name=httpOnly,proto3" json:"httpOnly,omitempty"`
	Secure   bool   `protobuf:"varint,2,opt,name=secure,proto3" json:"secure,omitempty"`
	Domain   string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Path     string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	MaxAge   string `protobuf:"bytes,5,opt,name=maxAge,proto3" json:"maxAge,omitempty"`
}

func (x *CookieOptions) Reset() {
	*x = CookieOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_filters_http_proto_ensure_variables_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CookieOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CookieOptions) ProtoMessage() {}

func (x *CookieOptions) ProtoReflect() protoreflect.Message {
	mi := &file_source_filters_http_proto_ensure_variables_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CookieOptions.ProtoReflect.Descriptor instead.
func (*CookieOptions) Descriptor() ([]byte, []int) {
	return file_source_filters_http_proto_ensure_variables_proto_rawDescGZIP(), []int{0}
}

func (x *CookieOptions) GetHttpOnly() bool {
	if x != nil {
		return x.HttpOnly
	}
	return false
}

func (x *CookieOptions) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *CookieOptions) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CookieOptions) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CookieOptions) GetMaxAge() string {
	if x != nil {
		return x.MaxAge
	}
	return ""
}

type EnsureVariablesConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rules []*EnsureVariablesConfig_Rule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
}

func (x *EnsureVariablesConfig) Reset() {
	*x = EnsureVariablesConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_filters_http_proto_ensure_variables_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnsureVariablesConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureVariablesConfig) ProtoMessage() {}

func (x *EnsureVariablesConfig) ProtoReflect() protoreflect.Message {
	mi := &file_source_filters_http_proto_ensure_variables_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureVariablesConfig.ProtoReflect.Descriptor instead.
func (*EnsureVariablesConfig) Descriptor() ([]byte, []int) {
	return file_source_filters_http_proto_ensure_variables_proto_rawDescGZIP(), []int{1}
}

func (x *EnsureVariablesConfig) GetRules() []*EnsureVariablesConfig_Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type EnsureVariablesConfig_Rule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key                 string                               `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Location            LocationType                         `protobuf:"varint,2,opt,name=location,proto3,enum=greymatter_io.gm_proxy.source.filters.http.LocationType" json:"location,omitempty"`
	MetadataFilter      string                               `protobuf:"bytes,3,opt,name=metadataFilter,proto3" json:"metadataFilter,omitempty"`
	Enforce             bool                                 `protobuf:"varint,4,opt,name=enforce,proto3" json:"enforce,omitempty"`
	EnforceResponseCode int32                                `protobuf:"varint,5,opt,name=enforceResponseCode,proto3" json:"enforceResponseCode,omitempty"`
	RemoveOriginal      bool                                 `protobuf:"varint,6,opt,name=removeOriginal,proto3" json:"removeOriginal,omitempty"`
	Value               *EnsureVariablesConfig_Rule_Value    `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	CopyTo              []*EnsureVariablesConfig_Rule_CopyTo `protobuf:"bytes,8,rep,name=copyTo,proto3" json:"copyTo,omitempty"`
}

func (x *EnsureVariablesConfig_Rule) Reset() {
	*x = EnsureVariablesConfig_Rule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_filters_http_proto_ensure_variables_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnsureVariablesConfig_Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureVariablesConfig_Rule) ProtoMessage() {}

func (x *EnsureVariablesConfig_Rule) ProtoReflect() protoreflect.Message {
	mi := &file_source_filters_http_proto_ensure_variables_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureVariablesConfig_Rule.ProtoReflect.Descriptor instead.
func (*EnsureVariablesConfig_Rule) Descriptor() ([]byte, []int) {
	return file_source_filters_http_proto_ensure_variables_proto_rawDescGZIP(), []int{1, 0}
}

func (x *EnsureVariablesConfig_Rule) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EnsureVariablesConfig_Rule) GetLocation() LocationType {
	if x != nil {
		return x.Location
	}
	return LocationType_header
}

func (x *EnsureVariablesConfig_Rule) GetMetadataFilter() string {
	if x != nil {
		return x.MetadataFilter
	}
	return ""
}

func (x *EnsureVariablesConfig_Rule) GetEnforce() bool {
	if x != nil {
		return x.Enforce
	}
	return false
}

func (x *EnsureVariablesConfig_Rule) GetEnforceResponseCode() int32 {
	if x != nil {
		return x.EnforceResponseCode
	}
	return 0
}

func (x *EnsureVariablesConfig_Rule) GetRemoveOriginal() bool {
	if x != nil {
		return x.RemoveOriginal
	}
	return false
}

func (x *EnsureVariablesConfig_Rule) GetValue() *EnsureVariablesConfig_Rule_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *EnsureVariablesConfig_Rule) GetCopyTo() []*EnsureVariablesConfig_Rule_CopyTo {
	if x != nil {
		return x.CopyTo
	}
	return nil
}

type EnsureVariablesConfig_Rule_Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchType   EnsureVariablesConfig_Rule_Value_MatchType `protobuf:"varint,1,opt,name=matchType,proto3,enum=greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig_Rule_Value_MatchType" json:"matchType,omitempty"`
	MatchString string                                     `protobuf:"bytes,2,opt,name=matchString,proto3" json:"matchString,omitempty"`
}

func (x *EnsureVariablesConfig_Rule_Value) Reset() {
	*x = EnsureVariablesConfig_Rule_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_filters_http_proto_ensure_variables_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnsureVariablesConfig_Rule_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureVariablesConfig_Rule_Value) ProtoMessage() {}

func (x *EnsureVariablesConfig_Rule_Value) ProtoReflect() protoreflect.Message {
	mi := &file_source_filters_http_proto_ensure_variables_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureVariablesConfig_Rule_Value.ProtoReflect.Descriptor instead.
func (*EnsureVariablesConfig_Rule_Value) Descriptor() ([]byte, []int) {
	return file_source_filters_http_proto_ensure_variables_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *EnsureVariablesConfig_Rule_Value) GetMatchType() EnsureVariablesConfig_Rule_Value_MatchType {
	if x != nil {
		return x.MatchType
	}
	return EnsureVariablesConfig_Rule_Value_exact
}

func (x *EnsureVariablesConfig_Rule_Value) GetMatchString() string {
	if x != nil {
		return x.MatchString
	}
	return ""
}

type EnsureVariablesConfig_Rule_CopyTo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location      LocationType                                `protobuf:"varint,1,opt,name=location,proto3,enum=greymatter_io.gm_proxy.source.filters.http.LocationType" json:"location,omitempty"`
	Key           string                                      `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Direction     EnsureVariablesConfig_Rule_CopyTo_Direction `protobuf:"varint,3,opt,name=direction,proto3,enum=greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig_Rule_CopyTo_Direction" json:"direction,omitempty"`
	CookieOptions *CookieOptions                              `protobuf:"bytes,4,opt,name=cookieOptions,proto3" json:"cookieOptions,omitempty"`
}

func (x *EnsureVariablesConfig_Rule_CopyTo) Reset() {
	*x = EnsureVariablesConfig_Rule_CopyTo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_filters_http_proto_ensure_variables_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnsureVariablesConfig_Rule_CopyTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureVariablesConfig_Rule_CopyTo) ProtoMessage() {}

func (x *EnsureVariablesConfig_Rule_CopyTo) ProtoReflect() protoreflect.Message {
	mi := &file_source_filters_http_proto_ensure_variables_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureVariablesConfig_Rule_CopyTo.ProtoReflect.Descriptor instead.
func (*EnsureVariablesConfig_Rule_CopyTo) Descriptor() ([]byte, []int) {
	return file_source_filters_http_proto_ensure_variables_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *EnsureVariablesConfig_Rule_CopyTo) GetLocation() LocationType {
	if x != nil {
		return x.Location
	}
	return LocationType_header
}

func (x *EnsureVariablesConfig_Rule_CopyTo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EnsureVariablesConfig_Rule_CopyTo) GetDirection() EnsureVariablesConfig_Rule_CopyTo_Direction {
	if x != nil {
		return x.Direction
	}
	return EnsureVariablesConfig_Rule_CopyTo_default
}

func (x *EnsureVariablesConfig_Rule_CopyTo) GetCookieOptions() *CookieOptions {
	if x != nil {
		return x.CookieOptions
	}
	return nil
}

var File_source_filters_http_proto_ensure_variables_proto protoreflect.FileDescriptor

var file_source_filters_http_proto_ensure_variables_proto_rawDesc = []byte{
	0x0a, 0x30, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73,
	0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x73, 0x75,
	0x72, 0x65, 0x2d, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x2a, 0x67, 0x72, 0x65, 0x79, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x69,
	0x6f, 0x2e, 0x67, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x22, 0x87,
	0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x74, 0x74, 0x70, 0x4f, 0x6e, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x68, 0x74, 0x74, 0x70, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x65,
	0x63, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x78, 0x41, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x61, 0x78, 0x41, 0x67, 0x65, 0x22, 0xb4, 0x09, 0x0a, 0x15, 0x45, 0x6e, 0x73,
	0x75, 0x72, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x5c, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x46, 0x2e, 0x67, 0x72, 0x65, 0x79, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x69,
	0x6f, 0x2e, 0x67, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x45,
	0x6e, 0x73, 0x75, 0x72, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73,
	0x1a, 0xbc, 0x08, 0x0a, 0x04, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x54, 0x0a, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x38, 0x2e,
	0x67, 0x72, 0x65, 0x79, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x6f, 0x2e, 0x67, 0x6d,
	0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x66,
	0x6f, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x66, 0x6f,
	0x72, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x65, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x13, 0x65, 0x6e, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x62, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4c, 0x2e, 0x67,
	0x72, 0x65, 0x79, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x6f, 0x2e, 0x67, 0x6d, 0x5f,
	0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x45, 0x6e, 0x73, 0x75, 0x72, 0x65,
	0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x52, 0x75, 0x6c, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x65, 0x0a, 0x06, 0x63, 0x6f, 0x70, 0x79, 0x54, 0x6f, 0x18, 0x08, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x4d, 0x2e, 0x67, 0x72, 0x65, 0x79, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x69,
	0x6f, 0x2e, 0x67, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x45,
	0x6e, 0x73, 0x75, 0x72, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x54, 0x6f,
	0x52, 0x06, 0x63, 0x6f, 0x70, 0x79, 0x54, 0x6f, 0x1a, 0xda, 0x01, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x74, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x56, 0x2e, 0x67, 0x72, 0x65, 0x79, 0x6d, 0x61, 0x74, 0x74,
	0x65, 0x72, 0x5f, 0x69, 0x6f, 0x2e, 0x67, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x68, 0x74,
	0x74, 0x70, 0x2e, 0x45, 0x6e, 0x73, 0x75, 0x72, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x39, 0x0a, 0x09, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x65, 0x78, 0x61, 0x63, 0x74,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x72, 0x65,
	0x67, 0x65, 0x78, 0x10, 0x03, 0x1a, 0x87, 0x03, 0x0a, 0x06, 0x43, 0x6f, 0x70, 0x79, 0x54, 0x6f,
	0x12, 0x54, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x38, 0x2e, 0x67, 0x72, 0x65, 0x79, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x5f,
	0x69, 0x6f, 0x2e, 0x67, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x75, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x57, 0x2e, 0x67, 0x72,
	0x65, 0x79, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x6f, 0x2e, 0x67, 0x6d, 0x5f, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x45, 0x6e, 0x73, 0x75, 0x72, 0x65, 0x56,
	0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52,
	0x75, 0x6c, 0x65, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x54, 0x6f, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x5f, 0x0a, 0x0d, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x67, 0x72, 0x65, 0x79, 0x6d, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x5f, 0x69, 0x6f, 0x2e, 0x67, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x68,
	0x74, 0x74, 0x70, 0x2e, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x0d, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x3d, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a,
	0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x62, 0x6f, 0x74, 0x68, 0x10, 0x03, 0x2a,
	0x45, 0x0a, 0x0c, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0a, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x63,
	0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x10, 0x03, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x65, 0x79, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x2d,
	0x69, 0x6f, 0x2f, 0x67, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_source_filters_http_proto_ensure_variables_proto_rawDescOnce sync.Once
	file_source_filters_http_proto_ensure_variables_proto_rawDescData = file_source_filters_http_proto_ensure_variables_proto_rawDesc
)

func file_source_filters_http_proto_ensure_variables_proto_rawDescGZIP() []byte {
	file_source_filters_http_proto_ensure_variables_proto_rawDescOnce.Do(func() {
		file_source_filters_http_proto_ensure_variables_proto_rawDescData = protoimpl.X.CompressGZIP(file_source_filters_http_proto_ensure_variables_proto_rawDescData)
	})
	return file_source_filters_http_proto_ensure_variables_proto_rawDescData
}

var file_source_filters_http_proto_ensure_variables_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_source_filters_http_proto_ensure_variables_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_source_filters_http_proto_ensure_variables_proto_goTypes = []interface{}{
	(LocationType)(0), // 0: greymatter_io.gm_proxy.source.filters.http.LocationType
	(EnsureVariablesConfig_Rule_Value_MatchType)(0),  // 1: greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule.Value.MatchType
	(EnsureVariablesConfig_Rule_CopyTo_Direction)(0), // 2: greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule.CopyTo.Direction
	(*CookieOptions)(nil),                            // 3: greymatter_io.gm_proxy.source.filters.http.CookieOptions
	(*EnsureVariablesConfig)(nil),                    // 4: greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig
	(*EnsureVariablesConfig_Rule)(nil),               // 5: greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule
	(*EnsureVariablesConfig_Rule_Value)(nil),         // 6: greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule.Value
	(*EnsureVariablesConfig_Rule_CopyTo)(nil),        // 7: greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule.CopyTo
}
var file_source_filters_http_proto_ensure_variables_proto_depIdxs = []int32{
	5, // 0: greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.rules:type_name -> greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule
	0, // 1: greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule.location:type_name -> greymatter_io.gm_proxy.source.filters.http.LocationType
	6, // 2: greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule.value:type_name -> greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule.Value
	7, // 3: greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule.copyTo:type_name -> greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule.CopyTo
	1, // 4: greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule.Value.matchType:type_name -> greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule.Value.MatchType
	0, // 5: greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule.CopyTo.location:type_name -> greymatter_io.gm_proxy.source.filters.http.LocationType
	2, // 6: greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule.CopyTo.direction:type_name -> greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule.CopyTo.Direction
	3, // 7: greymatter_io.gm_proxy.source.filters.http.EnsureVariablesConfig.Rule.CopyTo.cookieOptions:type_name -> greymatter_io.gm_proxy.source.filters.http.CookieOptions
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_source_filters_http_proto_ensure_variables_proto_init() }
func file_source_filters_http_proto_ensure_variables_proto_init() {
	if File_source_filters_http_proto_ensure_variables_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_source_filters_http_proto_ensure_variables_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CookieOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_source_filters_http_proto_ensure_variables_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnsureVariablesConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_source_filters_http_proto_ensure_variables_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnsureVariablesConfig_Rule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_source_filters_http_proto_ensure_variables_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnsureVariablesConfig_Rule_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_source_filters_http_proto_ensure_variables_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnsureVariablesConfig_Rule_CopyTo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_source_filters_http_proto_ensure_variables_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_source_filters_http_proto_ensure_variables_proto_goTypes,
		DependencyIndexes: file_source_filters_http_proto_ensure_variables_proto_depIdxs,
		EnumInfos:         file_source_filters_http_proto_ensure_variables_proto_enumTypes,
		MessageInfos:      file_source_filters_http_proto_ensure_variables_proto_msgTypes,
	}.Build()
	File_source_filters_http_proto_ensure_variables_proto = out.File
	file_source_filters_http_proto_ensure_variables_proto_rawDesc = nil
	file_source_filters_http_proto_ensure_variables_proto_goTypes = nil
	file_source_filters_http_proto_ensure_variables_proto_depIdxs = nil
}
