// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.21.5
// source: source/filters/http/proto/impersonation.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ImpersonationConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Servers       string `protobuf:"bytes,1,opt,name=servers,proto3" json:"servers,omitempty"`
	CaseSensitive bool   `protobuf:"varint,2,opt,name=caseSensitive,proto3" json:"caseSensitive,omitempty"`
}

func (x *ImpersonationConfig) Reset() {
	*x = ImpersonationConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_filters_http_proto_impersonation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImpersonationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpersonationConfig) ProtoMessage() {}

func (x *ImpersonationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_source_filters_http_proto_impersonation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpersonationConfig.ProtoReflect.Descriptor instead.
func (*ImpersonationConfig) Descriptor() ([]byte, []int) {
	return file_source_filters_http_proto_impersonation_proto_rawDescGZIP(), []int{0}
}

func (x *ImpersonationConfig) GetServers() string {
	if x != nil {
		return x.Servers
	}
	return ""
}

func (x *ImpersonationConfig) GetCaseSensitive() bool {
	if x != nil {
		return x.CaseSensitive
	}
	return false
}

var File_source_filters_http_proto_impersonation_proto protoreflect.FileDescriptor

var file_source_filters_http_proto_impersonation_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73,
	0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6d, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x2a, 0x67, 0x72, 0x65, 0x79, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x6f, 0x2e, 0x67,
	0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x22, 0x55, 0x0a, 0x13, 0x49,
	0x6d, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x0d,
	0x63, 0x61, 0x73, 0x65, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0d, 0x63, 0x61, 0x73, 0x65, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69,
	0x76, 0x65, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x72, 0x65, 0x79, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x2d, 0x69, 0x6f, 0x2f, 0x67,
	0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_source_filters_http_proto_impersonation_proto_rawDescOnce sync.Once
	file_source_filters_http_proto_impersonation_proto_rawDescData = file_source_filters_http_proto_impersonation_proto_rawDesc
)

func file_source_filters_http_proto_impersonation_proto_rawDescGZIP() []byte {
	file_source_filters_http_proto_impersonation_proto_rawDescOnce.Do(func() {
		file_source_filters_http_proto_impersonation_proto_rawDescData = protoimpl.X.CompressGZIP(file_source_filters_http_proto_impersonation_proto_rawDescData)
	})
	return file_source_filters_http_proto_impersonation_proto_rawDescData
}

var file_source_filters_http_proto_impersonation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_source_filters_http_proto_impersonation_proto_goTypes = []interface{}{
	(*ImpersonationConfig)(nil), // 0: greymatter_io.gm_proxy.source.filters.http.ImpersonationConfig
}
var file_source_filters_http_proto_impersonation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_source_filters_http_proto_impersonation_proto_init() }
func file_source_filters_http_proto_impersonation_proto_init() {
	if File_source_filters_http_proto_impersonation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_source_filters_http_proto_impersonation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImpersonationConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_source_filters_http_proto_impersonation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_source_filters_http_proto_impersonation_proto_goTypes,
		DependencyIndexes: file_source_filters_http_proto_impersonation_proto_depIdxs,
		MessageInfos:      file_source_filters_http_proto_impersonation_proto_msgTypes,
	}.Build()
	File_source_filters_http_proto_impersonation_proto = out.File
	file_source_filters_http_proto_impersonation_proto_rawDesc = nil
	file_source_filters_http_proto_impersonation_proto_goTypes = nil
	file_source_filters_http_proto_impersonation_proto_depIdxs = nil
}
