// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.21.5
// source: source/filters/http/proto/oauth.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OauthConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provider       string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ClientId       string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret   string `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	ServerName     string `protobuf:"bytes,4,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerInsecure bool   `protobuf:"varint,5,opt,name=server_insecure,json=serverInsecure,proto3" json:"server_insecure,omitempty"`
	SessionSecret  string `protobuf:"bytes,6,opt,name=session_secret,json=sessionSecret,proto3" json:"session_secret,omitempty"`
	Domain         string `protobuf:"bytes,7,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *OauthConfig) Reset() {
	*x = OauthConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_filters_http_proto_oauth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OauthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthConfig) ProtoMessage() {}

func (x *OauthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_source_filters_http_proto_oauth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthConfig.ProtoReflect.Descriptor instead.
func (*OauthConfig) Descriptor() ([]byte, []int) {
	return file_source_filters_http_proto_oauth_proto_rawDescGZIP(), []int{0}
}

func (x *OauthConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OauthConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OauthConfig) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *OauthConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *OauthConfig) GetServerInsecure() bool {
	if x != nil {
		return x.ServerInsecure
	}
	return false
}

func (x *OauthConfig) GetSessionSecret() string {
	if x != nil {
		return x.SessionSecret
	}
	return ""
}

func (x *OauthConfig) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type OauthRouteConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *OauthRouteConfig) Reset() {
	*x = OauthRouteConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_source_filters_http_proto_oauth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OauthRouteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthRouteConfig) ProtoMessage() {}

func (x *OauthRouteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_source_filters_http_proto_oauth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthRouteConfig.ProtoReflect.Descriptor instead.
func (*OauthRouteConfig) Descriptor() ([]byte, []int) {
	return file_source_filters_http_proto_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *OauthRouteConfig) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

var File_source_filters_http_proto_oauth_proto protoreflect.FileDescriptor

var file_source_filters_http_proto_oauth_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73,
	0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2a, 0x67, 0x72, 0x65, 0x79, 0x6d, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x5f, 0x69, 0x6f, 0x2e, 0x67, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x68,
	0x74, 0x74, 0x70, 0x22, 0xf4, 0x01, 0x0a, 0x0b, 0x4f, 0x61, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x2a, 0x0a, 0x10, 0x4f, 0x61,
	0x75, 0x74, 0x68, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x65, 0x79, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x72, 0x2d,
	0x69, 0x6f, 0x2f, 0x67, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_source_filters_http_proto_oauth_proto_rawDescOnce sync.Once
	file_source_filters_http_proto_oauth_proto_rawDescData = file_source_filters_http_proto_oauth_proto_rawDesc
)

func file_source_filters_http_proto_oauth_proto_rawDescGZIP() []byte {
	file_source_filters_http_proto_oauth_proto_rawDescOnce.Do(func() {
		file_source_filters_http_proto_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(file_source_filters_http_proto_oauth_proto_rawDescData)
	})
	return file_source_filters_http_proto_oauth_proto_rawDescData
}

var file_source_filters_http_proto_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_source_filters_http_proto_oauth_proto_goTypes = []interface{}{
	(*OauthConfig)(nil),      // 0: greymatter_io.gm_proxy.source.filters.http.OauthConfig
	(*OauthRouteConfig)(nil), // 1: greymatter_io.gm_proxy.source.filters.http.OauthRouteConfig
}
var file_source_filters_http_proto_oauth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_source_filters_http_proto_oauth_proto_init() }
func file_source_filters_http_proto_oauth_proto_init() {
	if File_source_filters_http_proto_oauth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_source_filters_http_proto_oauth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OauthConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_source_filters_http_proto_oauth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OauthRouteConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_source_filters_http_proto_oauth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_source_filters_http_proto_oauth_proto_goTypes,
		DependencyIndexes: file_source_filters_http_proto_oauth_proto_depIdxs,
		MessageInfos:      file_source_filters_http_proto_oauth_proto_msgTypes,
	}.Build()
	File_source_filters_http_proto_oauth_proto = out.File
	file_source_filters_http_proto_oauth_proto_rawDesc = nil
	file_source_filters_http_proto_oauth_proto_goTypes = nil
	file_source_filters_http_proto_oauth_proto_depIdxs = nil
}
